version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Download .NET Core 2.0 Preview 1 SDK and add to PATH
  - ps: $urlCurrent = "https://download.microsoft.com/download/0/6/5/0656B047-5F2F-4281-A851-F30776F8616D/dotnet-dev-win-x64.2.0.0-preview1-005977.zip"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFileCurrent = [System.IO.Path]::GetTempFileName()
  - ps: (New-Object System.Net.WebClient).DownloadFile($urlCurrent, $tempFileCurrent)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFileCurrent, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore .\diagrammatically.AvaloniaUi\diagrammatically.AvaloniaUi.csproj --verbosity m
build_script:
  - cmd: dotnet publish .\diagrammatically.AvaloniaUi\diagrammatically.AvaloniaUi.csproj
after_build:
  - cmd: 7z a .\diagrammatically.AvaloniaUi\diagrammatically.AvaloniaUi1.0.0.zip .\diagrammatically.AvaloniaUi\bin\Debug\netcoreapp2.0\publish\
artifacts:
 - path: .\diagrammatically.AvaloniaUi\diagrammatically.AvaloniaUi*.zip
   name: diagrammatically.AvaloniaUi
   type: zip
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./diagrammatically.Domein.UnitTest/diagrammatically.Domein.UnitTest.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd diagrammatically.Domein.UnitTest
  - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off
